version: "3.3"

services:
  server_part5:
    build: .
    container_name: server_part5
    tty: true
  part6:
    image: nginx
    container_name: server_part6
    ports:
      - 80:8080
    depends_on:
      - server_part5
    volumes:
      - ./part6/nginx.conf:/etc/nginx/nginx.conf